[package]
name = "evm-guardian"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.20", features = ["full"]}
tokio = { version = "1.46.1", features = ["full"] }
eyre = "0.6"
futures = "0.3"
